"""
All 48 custom node repository URLs.
To add a new node: append its .git URL to NODE_URLS.
"""

NODE_URLS: list[str] = [
    "https://github.com/ltdrdata/ComfyUI-Manager.git",
    "https://codeberg.org/Gourieff/comfyui-reactor-node.git",       # NOTE: codeberg, not GitHub
    "https://github.com/ltdrdata/ComfyUI-Impact-Pack.git",
    "https://github.com/ltdrdata/ComfyUI-Impact-Subpack.git",
    "https://github.com/Fannovel16/comfyui_controlnet_aux.git",
    "https://github.com/city96/ComfyUI-GGUF.git",
    "https://github.com/rgthree/rgthree-comfy.git",
    "https://github.com/yolain/ComfyUI-Easy-Use.git",
    "https://github.com/kijai/ComfyUI-KJNodes.git",
    "https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git",
    "https://github.com/cubiq/ComfyUI_essentials.git",
    "https://github.com/wallish77/wlsh_nodes.git",
    "https://github.com/vrgamegirl19/comfyui-vrgamedevgirl.git",
    "https://github.com/ClownsharkBatwing/RES4LYF.git",
    "https://github.com/kijai/ComfyUI-LivePortraitKJ.git",
    "https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait.git",
    "https://github.com/kijai/ComfyUI-Florence2.git",
    "https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced.git",
    "https://github.com/kijai/ComfyUI-HunyuanVideoWrapper.git",
    "https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git",
    "https://github.com/WASasquatch/was-node-suite-comfyui.git",
    "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git",
    "https://github.com/TinyTerra/ComfyUI_tinyterraNodes.git",
    "https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes.git",
    "https://github.com/Smirnov75/ComfyUI-mxToolkit.git",
    "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes.git",
    "https://github.com/chrisgoringe/cg-use-everywhere.git",
    "https://github.com/XLabs-AI/x-flux-comfyui.git",
    "https://github.com/logtd/ComfyUI-LTXTricks.git",
    "https://github.com/SeaArtLab/ComfyUI-Long-CLIP.git",
    "https://github.com/jamesWalker55/comfyui-various.git",
    "https://github.com/JPS-GER/ComfyUI_JPS-Nodes.git",
    "https://github.com/Jonseed/ComfyUI-Detail-Daemon.git",
    "https://github.com/kijai/ComfyUI-WanVideoWrapper.git",
    "https://github.com/Zehong-Ma/ComfyUI-MagCache.git",
    "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation.git",
    "https://github.com/mit-han-lab/ComfyUI-nunchaku.git",
    "https://github.com/ChenDarYen/ComfyUI-NAG.git",
    "https://github.com/Draek2077/comfyui-draekz-nodez.git",
    "https://github.com/crystian/ComfyUI-Crystools.git",
    "https://github.com/sipherxyz/comfyui-art-venture.git",
    "https://github.com/digitaljohn/comfyui-propost.git",
    "https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger.git",
    "https://github.com/jags111/efficiency-nodes-comfyui.git",
    "https://github.com/1038lab/ComfyUI-JoyCaption.git",
    "https://github.com/fairy-root/Flux-Prompt-Generator",
    "https://github.com/marduk191/ComfyUI-Fluxpromptenhancer",
    "https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch",
    "https://github.com/Draek2077/comfyui-draekz-workflowz.git",
]
